"""Add Organization and TenantResources tables

Revision ID: 4a55b97faca0
Revises: 6b918bc6c1db
Create Date: 2026-04-29 00:30:09.167617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a55b97faca0'
down_revision: Union[str, Sequence[str], None] = '6b918bc6c1db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_resources',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('qdrant_collection', sa.String(), nullable=True),
    sa.Column('redis_namespace', sa.String(), nullable=True),
    sa.Column('blob_prefix', sa.String(), nullable=True),
    sa.Column('secret_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plivo_status', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_resources')
    op.drop_table('organizations')
    # ### end Alembic commands ###
