"""Redesign TenantResources for Azure

Revision ID: c2a7eb6e4bfd
Revises: 4a55b97faca0
Create Date: 2026-04-29 00:41:37.254846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2a7eb6e4bfd'
down_revision: Union[str, Sequence[str], None] = '4a55b97faca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_resources', sa.Column('id', sa.UUID(), nullable=False))
    op.add_column('tenant_resources', sa.Column('azure_resource_group_name', sa.String(), nullable=True))
    op.add_column('tenant_resources', sa.Column('azure_region', sa.String(), nullable=True))
    op.add_column('tenant_resources', sa.Column('qdrant_collection_name', sa.String(), nullable=True))
    op.add_column('tenant_resources', sa.Column('storage_account_name', sa.String(), nullable=True))
    op.add_column('tenant_resources', sa.Column('storage_container_name', sa.String(), nullable=True))
    op.add_column('tenant_resources', sa.Column('key_vault_name', sa.String(), nullable=True))
    op.add_column('tenant_resources', sa.Column('plivo_phone_number', sa.String(), nullable=True))
    op.add_column('tenant_resources', sa.Column('provider_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenant_resources', sa.Column('provisioning_status', sa.String(), nullable=False))
    op.add_column('tenant_resources', sa.Column('provisioning_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('tenant_resources', sa.Column('cleanup_required', sa.Boolean(), nullable=True))
    op.add_column('tenant_resources', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('tenant_resources_organization_id_key'), 'tenant_resources', type_='unique')
    op.create_unique_constraint(None, 'tenant_resources', ['tenant_id'])
    op.drop_column('tenant_resources', 'status')
    op.drop_column('tenant_resources', 'qdrant_collection')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_resources', sa.Column('qdrant_collection', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenant_resources', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tenant_resources', type_='unique')
    op.create_unique_constraint(op.f('tenant_resources_organization_id_key'), 'tenant_resources', ['organization_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('tenant_resources', 'updated_at')
    op.drop_column('tenant_resources', 'cleanup_required')
    op.drop_column('tenant_resources', 'provisioning_steps')
    op.drop_column('tenant_resources', 'provisioning_status')
    op.drop_column('tenant_resources', 'provider_status')
    op.drop_column('tenant_resources', 'plivo_phone_number')
    op.drop_column('tenant_resources', 'key_vault_name')
    op.drop_column('tenant_resources', 'storage_container_name')
    op.drop_column('tenant_resources', 'storage_account_name')
    op.drop_column('tenant_resources', 'qdrant_collection_name')
    op.drop_column('tenant_resources', 'azure_region')
    op.drop_column('tenant_resources', 'azure_resource_group_name')
    op.drop_column('tenant_resources', 'id')
    # ### end Alembic commands ###
