from __future__ import annotations

import argparse
import asyncio
import ssl as py_ssl
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

import asyncpg


DEFAULT_CONNECTION = (
    "postgresql://Nokvo:Password123@nokvotest.postgres.database.azure.com:5432/postgres?ssl=require"
)


def build_connect_kwargs(connection_string: str) -> dict:
    if connection_string.startswith("postgres://"):
        connection_string = "postgresql://" + connection_string[len("postgres://") :]
    elif connection_string.startswith("postgresql+asyncpg://"):
        connection_string = "postgresql://" + connection_string[len("postgresql+asyncpg://") :]

    parsed = urlparse(connection_string)
    query_items = parse_qsl(parsed.query, keep_blank_values=True)
    filtered_query: list[tuple[str, str]] = []
    ssl_mode: str | None = None

    for key, value in query_items:
        if key.lower() in {"ssl", "sslmode"}:
            ssl_mode = value.strip().lower()
            continue
        filtered_query.append((key, value))

    normalized_dsn = urlunparse(parsed._replace(query=urlencode(filtered_query)))
    kwargs = {"dsn": normalized_dsn}
    if ssl_mode in {"require", "prefer", "allow", "true", "1", "yes"}:
        kwargs["ssl"] = True
    elif ssl_mode in {"verify-ca", "verify-full"}:
        kwargs["ssl"] = py_ssl.create_default_context()
    elif ssl_mode in {"disable", "false", "0", "no"}:
        kwargs["ssl"] = False
    return kwargs


DDL = """
CREATE SCHEMA IF NOT EXISTS demo_ecommerce;

CREATE TABLE IF NOT EXISTS demo_ecommerce.customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    phone TEXT,
    city TEXT NOT NULL,
    state TEXT NOT NULL,
    loyalty_tier TEXT NOT NULL DEFAULT 'standard',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS demo_ecommerce.products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    category TEXT NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'INR',
    stock_quantity INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS demo_ecommerce.orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL REFERENCES demo_ecommerce.customers(customer_id),
    order_number TEXT NOT NULL UNIQUE,
    order_status TEXT NOT NULL,
    payment_status TEXT NOT NULL,
    ordered_at TIMESTAMPTZ NOT NULL,
    shipping_city TEXT NOT NULL,
    shipping_state TEXT NOT NULL,
    order_total NUMERIC(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS demo_ecommerce.order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES demo_ecommerce.orders(order_id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES demo_ecommerce.products(product_id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12, 2) NOT NULL,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0
);
"""


SEED_SQL = """
INSERT INTO demo_ecommerce.customers (full_name, email, phone, city, state, loyalty_tier)
VALUES
    ('Anika Sharma', 'anika.sharma@example-store.test', '+91-9876500011', 'Bengaluru', 'Karnataka', 'gold'),
    ('Rahul Verma', 'rahul.verma@example-store.test', '+91-9876500012', 'Mumbai', 'Maharashtra', 'silver'),
    ('Priya Nair', 'priya.nair@example-store.test', '+91-9876500013', 'Kochi', 'Kerala', 'standard'),
    ('Arjun Mehta', 'arjun.mehta@example-store.test', '+91-9876500014', 'Ahmedabad', 'Gujarat', 'gold'),
    ('Neha Kapoor', 'neha.kapoor@example-store.test', '+91-9876500015', 'Delhi', 'Delhi', 'standard'),
    ('Karan Iyer', 'karan.iyer@example-store.test', '+91-9876500016', 'Chennai', 'Tamil Nadu', 'silver')
ON CONFLICT (email) DO NOTHING;

INSERT INTO demo_ecommerce.products (sku, product_name, category, unit_price, currency_code, stock_quantity, is_active)
VALUES
    ('SKU-TSHIRT-001', 'Essential Cotton T-Shirt', 'Apparel', 799.00, 'INR', 120, TRUE),
    ('SKU-JEANS-002', 'Slim Fit Denim Jeans', 'Apparel', 1899.00, 'INR', 80, TRUE),
    ('SKU-SHOE-003', 'Urban Runner Sneakers', 'Footwear', 3299.00, 'INR', 45, TRUE),
    ('SKU-BAG-004', 'Canvas Weekender Bag', 'Accessories', 2499.00, 'INR', 30, TRUE),
    ('SKU-WATCH-005', 'Classic Analog Watch', 'Accessories', 4599.00, 'INR', 25, TRUE),
    ('SKU-MUG-006', 'Ceramic Travel Mug', 'Home', 499.00, 'INR', 150, TRUE),
    ('SKU-LAMP-007', 'Desk Study Lamp', 'Home', 1599.00, 'INR', 60, TRUE),
    ('SKU-HEAD-008', 'Wireless Headphones', 'Electronics', 5499.00, 'INR', 40, TRUE)
ON CONFLICT (sku) DO NOTHING;

WITH customer_map AS (
    SELECT customer_id, email
    FROM demo_ecommerce.customers
),
order_seed AS (
    INSERT INTO demo_ecommerce.orders (
        customer_id,
        order_number,
        order_status,
        payment_status,
        ordered_at,
        shipping_city,
        shipping_state,
        order_total
    )
    VALUES
        ((SELECT customer_id FROM customer_map WHERE email = 'anika.sharma@example-store.test'), 'ORD-2026-1001', 'delivered', 'paid', '2026-04-04 10:15:00+05:30', 'Bengaluru', 'Karnataka', 4098.00),
        ((SELECT customer_id FROM customer_map WHERE email = 'rahul.verma@example-store.test'), 'ORD-2026-1002', 'shipped', 'paid', '2026-04-09 14:20:00+05:30', 'Mumbai', 'Maharashtra', 2499.00),
        ((SELECT customer_id FROM customer_map WHERE email = 'priya.nair@example-store.test'), 'ORD-2026-1003', 'processing', 'paid', '2026-04-13 18:45:00+05:30', 'Kochi', 'Kerala', 5998.00),
        ((SELECT customer_id FROM customer_map WHERE email = 'arjun.mehta@example-store.test'), 'ORD-2026-1004', 'delivered', 'paid', '2026-04-15 11:00:00+05:30', 'Ahmedabad', 'Gujarat', 799.00),
        ((SELECT customer_id FROM customer_map WHERE email = 'neha.kapoor@example-store.test'), 'ORD-2026-1005', 'cancelled', 'refunded', '2026-04-18 16:10:00+05:30', 'Delhi', 'Delhi', 1599.00)
    ON CONFLICT (order_number) DO NOTHING
    RETURNING order_id, order_number
)
SELECT 1;

INSERT INTO demo_ecommerce.order_items (order_id, product_id, quantity, unit_price, discount_amount)
SELECT o.order_id, p.product_id, seed.quantity, seed.unit_price, seed.discount_amount
FROM (
    VALUES
        ('ORD-2026-1001', 'SKU-TSHIRT-001', 2, 799.00, 0.00),
        ('ORD-2026-1001', 'SKU-SHOE-003', 1, 3299.00, 799.00),
        ('ORD-2026-1002', 'SKU-BAG-004', 1, 2499.00, 0.00),
        ('ORD-2026-1003', 'SKU-HEAD-008', 1, 5499.00, 0.00),
        ('ORD-2026-1003', 'SKU-MUG-006', 1, 499.00, 0.00),
        ('ORD-2026-1004', 'SKU-TSHIRT-001', 1, 799.00, 0.00),
        ('ORD-2026-1005', 'SKU-LAMP-007', 1, 1599.00, 0.00)
) AS seed(order_number, sku, quantity, unit_price, discount_amount)
JOIN demo_ecommerce.orders o ON o.order_number = seed.order_number
JOIN demo_ecommerce.products p ON p.sku = seed.sku
WHERE NOT EXISTS (
    SELECT 1
    FROM demo_ecommerce.order_items oi
    WHERE oi.order_id = o.order_id
      AND oi.product_id = p.product_id
);
"""


async def main() -> None:
    parser = argparse.ArgumentParser(description="Create demo ecommerce tables in PostgreSQL.")
    parser.add_argument("--connection-string", default=DEFAULT_CONNECTION)
    parser.add_argument("--drop", action="store_true", help="Drop the demo_ecommerce schema instead of creating it")
    args = parser.parse_args()

    conn = await asyncpg.connect(**build_connect_kwargs(args.connection_string))
    try:
        if args.drop:
            await conn.execute("DROP SCHEMA IF EXISTS demo_ecommerce CASCADE")
            rows = await conn.fetch(
                "SELECT table_name FROM information_schema.tables WHERE table_schema = $1 ORDER BY table_name",
                "demo_ecommerce",
            )
            print({"remaining_tables": [row["table_name"] for row in rows]})
            return

        async with conn.transaction():
            await conn.execute(DDL)
            await conn.execute(SEED_SQL)

        counts = {}
        for table_name in ("customers", "products", "orders", "order_items"):
            counts[table_name] = await conn.fetchval(f"SELECT COUNT(*) FROM demo_ecommerce.{table_name}")
        print(counts)
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
